{% set name = "konoha" %}
{% set version = "5.5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e87417d6c1ab57c616e7f4cdb5a7ae8c2c0855ec7a58bd900d903fddba29811

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry >=1.0.2
  run:
    - python >=3.8.0,<4.0.0
    - requests <3.0.0
  run_constrained:
    - janome >=0.5.0,<0.6.0
    - natto-py >=1.0.0,<2.0.0
    - kytea >=0.1.8,<0.2.0
    - sentencepiece >=0.1.85,<0.2.0
    - sudachipy >=0.6.8,<0.7.0
    - boto3 >=1.34.0,<2.0.0
    - fastapi <1.0.0
    - uvicorn <0.26.0
    - sudachidict-core 20230927
    - nagisa >=0.2.10,<0.3.0

test:
  imports:
    - konoha
    - konoha.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/konoha/
  summary: A tiny sentence/word tokenizer for Japanese text written in Python
  description: |
    Konoha is a Python library for providing easy-to-use integrated interface of
    various Japanese tokenziers, which enables you to switch a tokenizer and
    boost your pre-processing.
  license: MIT
  license_file: LICENSE
  doc_url: https://konoha.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/himkt/konoha

extra:
  recipe-maintainers:
    - BastianZim
    - himkt
